"""deleted images

Revision ID: 270a3557891b
Revises: e10ab3f13d38
Create Date: 2023-11-05 09:55:43.997863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270a3557891b'
down_revision = 'e10ab3f13d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associates', schema=None) as batch_op:
        batch_op.drop_column('associate_image')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('associate_image', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
