"""empty message

Revision ID: 39d1f05f3a1d
Revises: ea0fff79455c
Create Date: 2024-03-16 15:35:46.235023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d1f05f3a1d'
down_revision = 'ea0fff79455c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('shift_end')
        batch_op.drop_column('shift_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_start', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('shift_end', sa.TIME(), nullable=True))

    # ### end Alembic commands ###
