"""empty message

Revision ID: 74e09035dfb5
Revises: 39d1f05f3a1d
Create Date: 2024-03-17 00:52:16.628555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e09035dfb5'
down_revision = '39d1f05f3a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobclasses', schema=None) as batch_op:
        batch_op.drop_column('DayOfWeek')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobclasses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DayOfWeek', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
