"""empty message

Revision ID: ea0fff79455c
Revises: 511f556804f7
Create Date: 2024-01-15 13:45:49.287583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0fff79455c'
down_revision = '511f556804f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('shift_start',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('shift_end',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('shift_end',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('shift_start',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
